### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by convnets** [hszhao/semseg#18]
```
Totally 20210 samples in train set.
Starting Checking image&label pair train list...
Checking image&label pair train list done!
Traceback (most recent call last):
  File "tool/train.py", line 426, in <module>
    main()
  File "tool/train.py", line 107, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "tool/train.py", line 236, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, optimizer, epoch)
  File "tool/train.py", line 281, in train
    output, main_loss, aux_loss = model(input, target)
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xrlin/Desktop/semseg/model/pspnet.py", line 91, in forward
    x = self.layer4(x_tmp)
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xrlin/Desktop/semseg/model/resnet.py", line 87, in forward
    out = self.bn3(out)
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/home/xrlin/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1656, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 450.00 MiB (GPU 0; 23.65 GiB total capacity; 22.42 GiB already allocated; 105.12 MiB free; 311.16 MiB cached)

```

I tried to run every configuration in this project with one GPU (Titan RTX with 24GB memory), but it shows CUDA out of memory, which is wired because there are no other programs using the GPU. Do you have any suggestions for this issue?

**Comment by convnets** [comment]
BTW, my PyTorch version is 1.2.0, CUDA 10.0, Python 3.7.3

**Comment by zhixuanli** [comment]
Please paste your configuration yaml file here. @convnets

**Comment by convnets** [comment]
```
DATA:
  data_root: /media/xrlin/Datasets/datasets/VOCdevkit/VOC2012
  train_list: /media/xrlin/Datasets/datasets/VOCdevkit/VOC2012/list/train_aug.txt
  val_list: /media/xrlin/Datasets/datasets/VOCdevkit/VOC2012/list/val.txt
  classes: 21

TRAIN:
  arch: psp
  layers: 101
  sync_bn: True  # adopt sync_bn or not
  train_h: 473
  train_w: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.00125
  epochs: 150
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/voc2012/pspnet101/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: /media/xrlin/Datasets/datasets/VOCdevkit/VOC2012/list/val.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 473
  test_w: 473
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/voc2012/pspnet101/model/train_epoch_50.pth  # evaluation model path
  save_folder: exp/voc2012/pspnet101/result/epoch_50/val/ss  # results save folder
  colors_path: dataset/voc2012/voc2012_colors.txt  # path of dataset colors
  names_path: dataset/voc2012/voc2012_names.txt  # path of dataset category names

```


@zhixuanli  configuration file pasted. thanks for your reply.

**Comment by zhixuanli** [comment]
Your batchsize is too big, try with 2 or 4

**Comment by convnets** [comment]
By changing the batch size to a smaller number does work. Thanks. However, I encounter another problem. 
```
Traceback (most recent call last):
  File "tool/train.py", line 426, in <module>
    main()
  File "tool/train.py", line 105, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/home/xrlin/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/xrlin/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/xrlin/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/xrlin/Desktop/semseg/tool/train.py", line 236, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, optimizer, epoch)
  File "/home/xrlin/Desktop/semseg/tool/train.py", line 289, in train
    scaled_loss.backward()
  File "/home/xrlin/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/xrlin/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

Do you have any suggestions? @zhixuanli

**Comment by zhixuanli** [comment]
What is your NCCL version?

What is your pytorch version and cudnn version?

You can do some search to find how to check the version and paste here.

Maybe your NCCL version is too old.

Second, run this command before `python train.sh ***`

`export CUDA_LAUNCH_BLOCKING=1`

And maybe the error report would be different, if so, please paste here.

**Comment by convnets** [comment]
It seems like the dataloader using opencv has some problems:

`label = cv2.imread(label_path, cv2.IMREAD_GRAYSCALE)`

some of the loaded labels are: 

`label: [  0  14  38  52  75 113]
`

produced by `np.unique(label)`

**Comment by zhixuanli** [comment]
There seems no problem on loaded labels, but I have only run this code on CityScapes dataset, I don't know the format of VOC dataset.

`  what():  NCCL error in: /opt/conda/conda-bld/pytorch_1565272279342/work/torch/lib/c10d/../c10d/NCCLUtils.hpp:29, unhandled cuda error`

This implies that it's the error of NCCL.

Use this command to see more details:
`export NCCL_DEBUG=info`

You can upgrade your NCCL version if no other bugs can be found.

**Comment by convnets** [comment]
I fixed this issue  for PASCAL VOC 2012 dataset by changing the OpenCV loader to PIL loader:
`label = np.array(Image.open(label_path))`
 I'm not sure whether there is a OpenCV solution. @zhixuanli

**Comment by zhixuanli** [comment]
Congratulations!

It's confused why PIL is fine here. 
Have you tried `label = cv2.imread(label_path, 0)` ?
