### ISSUE TITLE
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by qysun291** [hszhao/semseg#76]
The GPU I used is RTX 8000 with 48G. However, I cannot run the it successfully and the error is "cuDNN error: CUDNN_STATUS_INTERNAL_ERROR". I notice that this appears because of the pspnet needs a more powerful GPU. I tried to decrease the batch size and resolution, and I find out that the occupation of GPU rise to a relative large valve and then decrease to about 11G. I speculate that the reason I fail to run the pspnet is the rapid rise of the occupation of GPU. The occupation is rather large (about 40G) even I set the batch size as 1. How can I address this?

**Comment by qysun291** [comment]
I have solved it.

**Comment by paidaxing485** [comment]
Hello, could you please tell me how to solve this problem

**Comment by AndreyStille** [comment]
> Hello, could you please tell me how to solve this problem

Seems no. He has suffered, so should we :(

**Comment by Prasadbp** [comment]
@AndreyStille  @paidaxing485  https://github.com/hszhao/semseg/issues/14#issue-495509965
